style = []
style.append('body {')
style.append('padding: 0;')
style.append('margin: 0;')
style.append('font: Helvetica, Arial, sans-serif;')
style.append('}')
style.append('')
style.append('h3 {')
style.append('margin: 0;')
style.append('}')
style.append('')
style.append('* {')
style.append('box-sizing: border-box;')
style.append('background-color: #24252a;')
style.append('}')
style.append('')
style.append('li,')
style.append('a,')
style.append('button,')
style.append('h3,')
style.append('div {')
style.append('color: #ffffff;')
style.append('text-decoration: none;')
style.append('}')
style.append('')
style.append('nav,')
style.append('.chapter_nav {')
style.append('display: flex;')
style.append('justify-content: space-between;')
style.append('align-items: center;')
style.append('padding: 0.1em 10%;')
style.append('}')
style.append('')
style.append('.footer {')
style.append('display: flex;')
style.append('justify-content: center;')
style.append('padding: 2em;')
style.append('margin-top: 2em;')
style.append('text-align: center;')
style.append('font-size: large;')
style.append('background-color: #1e1f24;')
style.append('')
style.append('box-shadow: inset 0 -0.6em 0 -0.35em rgba(0, 0, 0, 0.17);')
style.append('}')
style.append('')
style.append('.footer .content {')
style.append('display: flex;')
style.append('justify-content: center;')
style.append('')
style.append('padding: 1em 1.4em;')
style.append('')
style.append('transition: all 0.3s ease 0s;')
style.append('}')
style.append('')
style.append('.footer .content:hover {')
style.append('transition: all 0.3s ease 0s;')
style.append('')
style.append('box-shadow: inset 0 -5em 0 -2em rgba(0, 0, 0, 0.17);')
style.append('}')
style.append('')
style.append('.footer .content div {')
style.append('margin-right: 0.4em;')
style.append('}')
style.append('')
style.append('.footer a,')
style.append('.footer div {')
style.append('background-color: transparent;')
style.append('}')
style.append('')
style.append('.container {')
style.append('padding: 0px 10%;')
style.append('}')
style.append('')
style.append('.list li {')
style.append('list-style: none;')
style.append('}')
style.append('')
style.append('.list .header {')
style.append('display: inline-block;')
style.append('')
style.append('border-radius: 0.3em;')
style.append('')
style.append('text-transform: uppercase;')
style.append('padding: 0.6em 1.2em;')
style.append('')
style.append('margin-top: 1em;')
style.append('margin-bottom: 0.5em;')
style.append('')
style.append('background-color: rgba(0, 0, 0, 0.17);')
style.append('box-shadow: inset 0 -0.6em 0 -0.35em #383838;')
style.append('}')
style.append('')
style.append('.mt-2 {')
style.append('margin-top: 1.4em;')
style.append('}')
style.append('')
style.append('.divider {')
style.append('margin: 0px 9%;')
style.append('padding: 0.1em;')
style.append('')
style.append('box-shadow: inset 0 -0.6em 0 -0.35em rgba(0, 0, 0, 0.17);')
style.append('}')
style.append('')
style.append('.title {')
style.append('text-transform: uppercase;')
style.append('font-weight: bold;')
style.append('white-space: nowrap;')
style.append('overflow: hidden;')
style.append('text-overflow: ellipsis;')
style.append('}')
style.append('')
style.append('.nav_links,')
style.append('.chap_links {')
style.append('min-width: 21em;')
style.append('list-style: none;')
style.append('}')
style.append('')
style.append('.nav_links li,')
style.append('.chap_links li {')
style.append('display: inline-block;')
style.append('padding: 0px 0.5em;')
style.append('}')
style.append('')
style.append('.nav_links li a {')
style.append('border-radius: 0.3em;')
style.append('')
style.append('text-transform: uppercase;')
style.append('padding: 0.6em 1.2em;')
style.append('transition: all 0.3s ease 0s;')
style.append('box-shadow: inset 0 -0.6em 0 -0.35em #3369ff;')
style.append('}')
style.append('')
style.append('.nav_links li a:hover {')
style.append('transition: all 0.3s ease 0s;')
style.append('color: #3369ff;')
style.append('box-shadow: inset 0 -5em 0 -2.5em #121c3b;')
style.append('}')
style.append('')
style.append('.nav_links li a:active {')
style.append('transition: all 0.1s ease 0s;')
style.append('color: #3369ff;')
style.append('box-shadow: inset 0 -5em 0 -2.5em rgba(0, 0, 0, 0.17);')
style.append('}')
style.append('')
style.append('a.btn {')
style.append('display: inline-block;')
style.append('padding: 0.7em 1.4em;')
style.append('margin: 0 0.3em 0.3em 0;')
style.append('border-radius: 0.15em;')
style.append('box-sizing: border-box;')
style.append('text-decoration: none;')
style.append('font-family: "Roboto", sans-serif;')
style.append('text-transform: uppercase;')
style.append('font-weight: 400;')
style.append('color: #ffffff;')
style.append('background-color: #3369ff;')
style.append('box-shadow: inset 0 -0.6em 0 -0.35em rgba(0, 0, 0, 0.17);')
style.append('text-align: center;')
style.append('position: relative;')
style.append('}')
style.append('a.btn:active {')
style.append('top: 0.1em;')
style.append('}')
style.append('')
style.append('.page {')
style.append('display: block;')
style.append('margin: 0 auto 5px;')
style.append('z-index: 1 !important;')
style.append('}')
style.append('')
style.append('@media all and (max-width: 30em) {')
style.append('a.btn {')
style.append('display: block;')
style.append('max-width: 0.4em auto;')
style.append('}')
style.append('}')
